### PR TITLE
Assertion error fix

### PR DESCRIPTION
**Pull request by ScriptSlayer0**
Hello @HarbingerOfFire, I have been several days testing and trying to fix the assertion problems in the code, I would like you to check it before you compile it, I have tested it and it seems that it doesn't give any error in make.

### CODE REVIEW

**Comment by HarbingerOfFire** [comment]
Please rerun test.c to ensure the code didn't break with my changes.

**Comment by ScriptSlayer0** [comment]
`PS D:\github\BivitattusDatabase> cd "d:\github\BivitattusDatabase\" ; if ($?) { gcc test.c -o test } ; if ($?) { .\test }
In file included from database.h:1:0,
                 from test.c:3:
base.h: In function 'makedir':
base.h:43:13: error: too many arguments to function 'mkdir'
         if (mkdir(dir_name, 0755) != 0) {
             ^~~~~
In file included from c:\mingw\include\dos.h:64:0,
                 from c:\mingw\include\direct.h:53,
                 from base.h:9,
                 from database.h:1,
                 from test.c:3:
c:\mingw\include\io.h:516:38: note: declared here
 _CRTIMP __cdecl __MINGW_NOTHROW  int mkdir (const char *);
                                      ^~~~~`

**Comment by HarbingerOfFire** [comment]
please use the make file as described in the readme

**Comment by ScriptSlayer0** [comment]
(using make)
```
gcc -c -Wall -Werror -fpic database.c
In file included from database.c:1:
base.h:15:21: error: ‘_MAX_FNAME’ undeclared here (not in a function)
   15 | #define MAXFILENAME _MAX_FNAME //should be about 256 for most systems
      |                     ^~~~~~~~~~
base.h:21:20: note: in expansion of macro ‘MAXFILENAME’
   21 |     char tablename[MAXFILENAME];
      |                    ^~~~~~~~~~~
base.h: In function ‘catpath’:
base.h:51:17: error: unused variable ‘fullpath’ [-Werror=unused-variable]
   51 |     static char fullpath[PATHSIZE];
      |                 ^~~~~~~~
base.h:57:1: error: control reaches end of non-void function [-Werror=return-type]
   57 | }
      | ^
cc1: all warnings being treated as errors
make: *** [Makefile:26: compile] Error 1
```

**Comment by HarbingerOfFire** [comment]
retry the test file

**Comment by ScriptSlayer0** [comment]
```
gcc -c -Wall -Werror -fpic database.c
In file included from database.c:1:
base.h:15:21: error: ‘_MAX_FNAME’ undeclared here (not in a function)
   15 | #define MAXFILENAME _MAX_FNAME //should be about 256 for most systems
      |                     ^~~~~~~~~~
base.h:21:20: note: in expansion of macro ‘MAXFILENAME’
   21 |     char tablename[MAXFILENAME];
      |                    ^~~~~~~~~~~
base.h: In function ‘catpath’:
base.h:58:17: error: unused variable ‘fullpath’ [-Werror=unused-variable]
   58 |     static char fullpath[PATHSIZE];
      |                 ^~~~~~~~
base.h:64:1: error: control reaches end of non-void function [-Werror=return-type]
   64 | }
      | ^
cc1: all warnings being treated as errors
make: *** [Makefile:26: compile] Error 1
```

**Comment by ScriptSlayer0** [comment]
The output from test.c:
```
PS D:\github\BivitattusDatabase> cd "d:\github\BivitattusDatabase\" ; if ($?) { gcc test.c -o test } ; if ($?) { .\test }
Test table 1 exists: True
Test table 2 exists: True
check: working...
Result of the elimination from the table: Success
new check: working...
```
The other output running make & make clean:
```
scriptslayer0@ubuntu:/mnt/d/github/BivitattusDatabase$ make && make clean
gcc -c -Wall -Werror -fpic database.c
gcc -shared -o lib_bdb.so database.o
rm -f database.o
```

**Pull request merged**
